version: "2.4"

services:
  server:
    image: ${SERVER}
    build: ./impl-endpoints/${SERVER}
    container_name: server
    hostname: server
    stdin_open: true
    tty: true
    volumes:
      - ./certs:/certs:ro
    cap_add:
      - NET_ADMIN
    ulimits:
      memlock: 67108864
    networks:
      - interopnet

  client:
    image: ${CLIENT}
    build: ./impl-endpoints/${CLIENT}
    container_name: client
    hostname: client
    stdin_open: true
    tty: true
    volumes:
      - ./certs:/certs:ro
    cap_add:
      - NET_ADMIN
    ulimits:
      memlock: 67108864
    networks:
      - interopnet

networks:
  interopnet:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.167.0.0/24
        - subnet: fd00:cafe:cafe:0::/64
